<script lang="ts">
	import { goto } from '$app/navigation';
	import PackageEdit from '$lib/PackageEdit.svelte';
	import { formatNumber } from '$lib/util';
	import { getContext } from 'svelte';
	import type { Writable } from 'svelte/store';
    import { save } from '@tauri-apps/api/dialog';
    import { writeTextFile } from '@tauri-apps/api/fs';
	import MetadataEdit from '$lib/MetadataEdit.svelte';

    let error = ""; //message
    const MOD: Writable<App.ModData> = getContext('MOD');
    console.log($MOD);
    
    let lastScroll = 0; //used to set scroll back to last position after editing
    let editingIndex: number | null = null;
    let editingPackage: App.Package | null = null; //copy to allow cancelling
    let editingResearch: App.Research | null = null;
    let editingMeta: App.ModMetadata | null = null;
    let STATE: "editPackage" | "editMeta" | "preview" | null = null;

    let asideExpanded = false; //is mouse in aside bar

    function exitEdit() {
        editingIndex = editingPackage = editingResearch = editingMeta = null;
        STATE = null;
        setTimeout(() => window.scroll({top: lastScroll}), 0); //gay hacky thing waiting for table to render
    }

    function onPackageEditSave() {
        if(editingIndex != null) {
            const oldRes = findResearch(editingPackage!.name);
            if(editingPackage!.res < 2) {
                //has research
                if(!$MOD.research) $MOD.research = [];
                if(!oldRes) $MOD.research.push(editingResearch as App.Research); //add new research
                else $MOD.research[oldRes.id] = editingResearch as App.Research; //edit existing research
            } else {
                //doesn't have research
                if(oldRes && $MOD.research?.length)
                    $MOD.research = $MOD.research.filter((r, i) => i != oldRes.id) //remove research
            }

            $MOD.packages[editingIndex] = editingPackage as App.Package;
        }
        exitEdit();
    }

    function onMetaEditSave() {
        if(editingMeta) $MOD.meta = editingMeta;
        exitEdit();
    }

    function edit(id: number) {
        lastScroll = window.scrollY;
        editingIndex = id;
        editingPackage = JSON.parse(JSON.stringify($MOD.packages[id]));
        if(editingPackage && (editingPackage.res ?? -1) >= 1) editingResearch = JSON.parse(JSON.stringify(findResearch(editingPackage.name)?.res ?? null));
        STATE = "editPackage";
    }

    function editMeta() {
        editingMeta = JSON.parse(JSON.stringify($MOD.meta));
        STATE = "editMeta";
    }
    
    function findResearch(name: string) {
        if(!$MOD?.research?.length) return null;

        const id = $MOD.research.findIndex((a) => a.name === name);
        if(id < 0) return null;
        const res = $MOD.research[id];

        return {id, res};
    }
    
    function removeResearch(id: number) {
        $MOD.research?.splice(id, 1);
    }

    function removePackage(id: number) {
        const pckg = $MOD.packages[id];
        if(pckg.res < 2) {
            const res = findResearch(pckg.name);
            if(res?.id != null) removeResearch(res.id);
        }

        $MOD.packages.splice(id, 1);
        $MOD = $MOD;
        console.log($MOD);
    }

    function addPackage() {
        $MOD.packages.push(
            {build: 0, cost: 1000, img: "DIP14", maxClock: 5000, maxCore: "0", name: "DIP14", perf: 0, res: 2, stab: 0, time: 5, unit: 10}
        )
        edit($MOD.packages.length - 1);
    }

    const formatPackage = (p: App.Package) =>
        `${p.name}|${p.cost}|${p.time}|${p.unit}|${p.perf}|${p.stab}|${p.build}|${p.res}|${p.maxClock}|${p.maxCore}|${p.img};`

    //join entire research object using "|" and replace the last one with ";"
    const formatResearch = (r: App.Research) => {let s = ""; for(let i in r) s += (r as Record<string,any>)[i] + "|"; return s.replace(/.$/,";");}

    function formatHtMod(mod: App.ModData) {
        let string = `[Author: ${mod.meta.author}][Name: ${mod.meta.name}][Mod Version: ${mod.meta.version}][Supported Version: ${mod.meta.gameVersion}][Tool Version: ${mod.meta.toolVersion}]\n`
        string += "--Generated by Hardware Tycoon Mod Tool by Haxor--";

        if(mod.packages?.length) {
            string += "\nPackages{";
            for(const p of mod.packages) string += "\n" + formatPackage(p);
            string += "}";
        }
        if(mod.research?.length) {
            string += "\nResearch{";
            for(const r of mod.research) string += "\n" + formatResearch(r);
            string += "}";
        }

        return string;
    }

    async function saveMod() {
        try {
            const path = await save({
                filters: [{name: 'Mod file', extensions: ['htmod']}], 
                title: "Save " + $MOD.meta.name + " " + $MOD.meta.version})

            if(!path) return; //canceled
            await writeTextFile(path, formatHtMod($MOD));
        } catch(e) {
            error = e instanceof Error ? e.message : String(e);
        }
    }
</script>

<div class="main-container column scrollbar-dark">
{#if $MOD}
    <h2 class="row-center">
        <span>{$MOD.meta?.name}</span>
        <small>[{$MOD.meta?.version}]</small>
    </h2>
{/if}
{#if error}
    <p class="error-p">{error}</p>
{/if}

<main class="row flex-fill">
{#if STATE == "editPackage" && editingPackage}
    <PackageEdit bind:editing={editingPackage} bind:research={editingResearch} onCancel={exitEdit} onSave={onPackageEditSave}/>
{:else if $MOD}
    <div class="table-wrapper flex-fill">
    <aside class="column" class:aside-expand={asideExpanded} on:mouseenter={() => asideExpanded = true} on:mouseleave={() => asideExpanded = false}>
        <ul>
            <li class="row">
                <button class="btn-none" on:click={() => STATE = "preview"}>
                    <iconify-icon class="btn-menu" class:aside-active={STATE == "preview"} icon="ic:baseline-preview"/>
                    <span class="btn-menu-text">Preview R&D</span>
                </button>
            </li>
    
            <li class="row">
                <button class="btn-none" on:click={editMeta}>
                    <iconify-icon class="btn-menu" class:aside-active={STATE == "editMeta"} icon="ic:baseline-toc"/>
                    <span class="btn-menu-text">Mod settings</span>
                </button>
            </li>
    
            <li class="row">
                <button class="btn-none" on:click={saveMod}>
                    <iconify-icon class="btn-menu" icon="ic:baseline-save"/>
                    <span class="btn-menu-text">Save mod file</span>
                </button>
            </li>
    
            <li class="row">
                <button class="btn-none" on:click={() => goto("/")}>
                    <iconify-icon class="btn-menu" icon="ic:baseline-arrow-back"/>
                    <span class="btn-menu-text">Back to menu</span>
                </button>
            </li>
        </ul>
        </aside>

        {#if STATE == "preview"}
            <button on:click={() => STATE = null}>preview</button>
        {:else if STATE == "editMeta" && editingMeta}
            <MetadataEdit bind:meta={editingMeta} onCancel={exitEdit} onSave={onMetaEditSave}/>
        {:else if STATE != "editPackage"}
            <table class="package-table" style="{$MOD.packages.length ? "" : "width: 55%; --radius: 0;"}">
                {#if $MOD.packages?.length}
                <thead>
                    <tr>
                        <th></th>
                        <th></th>
                        <th>Package</th>
                        <th>Cost</th>
                        <th>Time</th>
                        <th>Unit</th>
                        <th>Perf.</th>
                        <th>Stability</th>
                        <th>Build</th>
                        <th></th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    {#each $MOD.packages as pckg, id}
                    <tr class="package-item" on:click={() => edit(id)}>
                        <td style="font-size: 67.5%;">#{id + 1}</td>
                        <td class="row"><img class="package-img" src="/package/{pckg.img}.png" alt=""></td>
                        <td>{pckg.name}</td>
                        <td>${formatNumber(Math.round(pckg.cost))}</td>
                        <td>{pckg.time}D</td>
                        <td>${Math.round(pckg.unit*100)/100}</td>
                        <td>{formatNumber(pckg.perf)}</td>
                        <td>{formatNumber(pckg.stab)}</td>
                        <td>{formatNumber(pckg.build)}</td>
                        <td>
                            {#if pckg.res < 1}
                            <iconify-icon icon="ic:baseline-science" title="Has associated research" style="opacity: 0.7;"/>
                            {/if}
                        </td>
                        <td>
                            <button class="btn-none btn-hover-highlight" on:click|stopPropagation={() => removePackage(id)}>
                                <iconify-icon icon="ic:baseline-delete"/>
                            </button>
                        </td>
                    </tr>
                    {/each}
                </tbody>
                {/if}
                <tr>
                    <td class="package-add-item" colspan="11">
                        <button type="button" on:click={addPackage} style="{$MOD.packages.length ? "" : "margin-top: 0;"}">
                            <iconify-icon icon="ic:baseline-add-circle-outline"/>
                        </button>
                    </td>
                </tr>
            </table>
        {/if}
    </div>
{:else}
<div class="column" style="margin: auto;">
    <h1>Uh oh!</h1>
    <p style="text-align: center;">
        Looks like the mod was loaded incorrectly.<br>
        Please reload the editor.
    </p>
    <button class="btn-blue" on:click={() => goto('/')}>Back</button>
</div>
{/if}
</main>
</div>

<style>
    h2 {
        font-weight: 400;
        background-color: var(--color-ht-primary);
    }
    h2 small {
        font-size: 1rem;
        margin-left: 10px;
    }
    
    .main-container {
        min-height: 100vh;
    }
    main {
        min-height: auto;
    }
    .table-wrapper {
        position: relative;
    }

    .package-table {
        padding: 0;
        margin: 14px auto;
        height: fit-content;
        background-color: rgba(255, 255, 255, 0.75);
        border-collapse: collapse;
        text-align: center;
        --radius: 12px;
        border-top-right-radius: var(--radius);
        border-top-left-radius: var(--radius);
    }
    .package-table td {
        padding: 2px 8px;
        padding-right: 18px;
    }
    .package-table td:last-child {
        padding-right: 8px;
    }
    .package-table th {
        cursor: default;
        padding: 8px 10px;
        background-color: var(--color-ht-primary);
    }
    .package-table th:first-child {
        border-top-left-radius: var(--radius);
    }
    .package-table th:last-child {
        border-top-right-radius: var(--radius);
    }

    .package-item {
        font-size: 1.25rem;
    }
    .package-item:hover {
        background-color: var(--color-highlight-blue);
        cursor: pointer;
    }
    .package-item button {
        font-size: 1.25rem;
    }
    .package-img {
        width: 48px;
        height: 48px;
    }

    .package-add-item {
        padding: 0 !important;
    }
    .package-add-item > button {
        width: 100%;
        background-color: rgba(174, 213, 129, 0.5);
        font-size: 1.5rem;
        padding: 6px;
        border: none;
        border-radius: 0;
        margin-top: 8px;
    }
    .package-add-item > button:hover {
        background-color: rgba(174, 213, 129, 1);
    }

    aside {
        position: absolute;
        top: 0;
        left: 0;
        align-items: flex-start;
        padding-top: 20px;
        background-color: rgba(255, 255, 255, 0.5);
        height: 100%;
        user-select: none;
        box-shadow: 3px 0 2px rgba(0,0,0, 0.25);
        transition: background 0.2s ease-out;
    }
    aside > ul {
        list-style: none;
        position: sticky;
        top: 20px;
        margin: 0;
        padding: 0;
    }
    aside li {
        align-items: center;
        margin-bottom: 8px;
        padding: 6px 12px;
    }
    aside li:hover {
        background-color: var(--color-ht-secondary);
    }
    aside li > button:focus {
        box-shadow: none;
    }
    .aside-active {
        background-color: var(--color-ht-secondary);
    }
    .btn-menu-text {
        max-width: 0;
        margin-left: 6px;
        font-size: 1.25rem;
        text-wrap: nowrap;
        line-height: 1;
        overflow: hidden;
        transition: max-width 0.2s ease-out;
    }
    .btn-menu:hover {
	    background-color: rgba(255, 255, 255, 0.5);
    }
    .aside-expand {
        background-color: rgba(255, 255, 255, 0.8);
    }
    .aside-expand .btn-menu {
        background-color: rgba(255, 255, 255, 1);
    }
    .aside-expand .btn-menu-text {
        max-width: 16ch;
    }

    .error-p {
        position: sticky;
        top: 0;
        margin: 0;
    }
</style>